version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/decx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/decx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/plugins/ard-framework"
    schedule:
      interval: "weekly"
