/**
 * PATH link tests: symlinks on POSIX, generated `.cmd` shims on Windows, and
 * the guarantee that a foreign file in the link directory is never overwritten
 * unless `--force` asks for it.
 */

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { binPath, provenanceFile } from '../src/config.ts';
import { venvLauncherText } from '../src/install.ts';
import { createLinks, linkFileName, linkName, shimText } from '../src/links.ts';

function tempDir(prefix = 'decx-links-'): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function store(home: string, ...names: string[]): void {
  fs.mkdirSync(path.dirname(binPath(home, names[0] as string)), { recursive: true });
  for (const name of names) {
    fs.writeFileSync(binPath(home, name), '#!/bin/sh\n', { mode: 0o755 });
  }
}

test('linkName strips the executable suffixes a store file may carry', () => {
  assert.equal(linkName('kuna'), 'kuna');
  assert.equal(linkName('kuna.exe'), 'kuna');
  assert.equal(linkName('droidasc.cmd'), 'droidasc');
  assert.equal(linkName('ASC.CMD'), 'ASC');
});

test('linkFileName adds .cmd on Windows only', () => {
  assert.equal(linkFileName('kuna', false), 'kuna');
  assert.equal(linkFileName('kuna', true), 'kuna.cmd');
  assert.equal(linkFileName('kuna.exe', true), 'kuna.exe');
});

test('createLinks links every managed executable into the link directory', () => {
  const home = tempDir();
  const linkDir = tempDir();
  store(home, 'kuna', 'decomp_dbg', 'slacomp');
  const outcomes = createLinks({ home, files: ['kuna', 'decomp_dbg', 'slacomp'], linkDir });
  assert.deepEqual(outcomes.map((outcome) => outcome.status), ['created', 'created', 'created']);
  let created = 0;
  for (const entry of fs.readdirSync(linkDir)) {
    created += 1;
    if (process.platform !== 'win32') {
      assert.ok(fs.lstatSync(path.join(linkDir, entry)).isSymbolicLink());
      assert.equal(fs.realpathSync(path.join(linkDir, entry)), fs.realpathSync(binPath(home, entry)));
    }
  }
  assert.equal(created, 3);
});

test('createLinks is idempotent', () => {
  const home = tempDir();
  const linkDir = tempDir();
  store(home, 'kuna');
  createLinks({ home, files: ['kuna'], linkDir });
  const again = createLinks({ home, files: ['kuna'], linkDir });
  assert.equal(again[0]?.status, 'unchanged');
});

test('createLinks never replaces a foreign file without force', () => {
  const home = tempDir();
  const linkDir = tempDir();
  store(home, 'kuna');
  const foreign = path.join(linkDir, linkFileName('kuna'));
  fs.writeFileSync(foreign, '#!/bin/sh\necho someone else\n', { mode: 0o755 });
  const outcomes = createLinks({ home, files: ['kuna'], linkDir });
  assert.equal(outcomes[0]?.status, 'conflict');
  assert.match(outcomes[0]?.reason ?? '', /not created by decx/);
  assert.equal(fs.readFileSync(foreign, 'utf8'), '#!/bin/sh\necho someone else\n');
  assert.equal(fs.lstatSync(foreign).isSymbolicLink(), false, 'the foreign file is not replaced by a link');
  // The conflict is reported, not fatal: the store keeps the managed executable.
  assert.ok(fs.existsSync(binPath(home, 'kuna')));
});

test('createLinks with force moves the foreign file aside', () => {
  const home = tempDir();
  const linkDir = tempDir();
  store(home, 'kuna');
  const foreign = path.join(linkDir, linkFileName('kuna'));
  fs.writeFileSync(foreign, '#!/bin/sh\necho someone else\n', { mode: 0o755 });
  const outcomes = createLinks({ home, files: ['kuna'], linkDir, force: true });
  assert.equal(outcomes[0]?.status, 'updated');
  const leftovers = fs.readdirSync(linkDir).filter((entry) => entry.startsWith('kuna.decx-old-'));
  assert.equal(leftovers.length, 1);
  const link = path.join(linkDir, linkFileName('kuna'));
  if (process.platform === 'win32') {
    assert.match(fs.readFileSync(link, 'utf8'), /Generated by decx install/);
  } else {
    assert.equal(fs.realpathSync(link), fs.realpathSync(binPath(home, 'kuna')));
  }
});

test('shimText carries the marker and forwards argv', () => {
  const text = shimText('C:\\Users\\me\\.decx\\bin\\kuna.exe');
  assert.match(text, /Generated by decx install/);
  assert.match(text, /"C:\\Users\\me\\\.decx\\bin\\kuna\.exe" %\*/);
  assert.match(text, /exit \/b %errorlevel%/);
  assert.ok(text.includes('\r\n'));
});

test('the store file and the PROVENANCE file are the only state', () => {
  // Guards the layout contract other modules rely on.
  const home = tempDir();
  store(home, 'kuna');
  assert.ok(fs.existsSync(binPath(home, 'kuna')));
  assert.match(provenanceFile(home, 'kuna'), /share[\\/]kuna[\\/]PROVENANCE$/);
});

test('a script launcher runs correctly through its PATH symlink', { skip: process.platform === 'win32' }, () => {
  // Regression: the launcher used to derive its root from $0, so executing it
  // through ~/.local/bin/<name> resolved the payload against the link's parent.
  const home = tempDir('decx-home-');
  const linkDir = tempDir('decx-links-');
  fs.mkdirSync(path.dirname(binPath(home, 'droidasc')), { recursive: true });
  fs.writeFileSync(
    binPath(home, 'droidasc'),
    venvLauncherText({ id: 'droidasc', platformOs: 'linux', venvBin: 'bin', venvPython: 'python', entry: 'main.py' }),
    { mode: 0o755 },
  );
  fs.mkdirSync(path.join(home, 'share', 'droidasc', 'venv', 'bin'), { recursive: true });
  fs.writeFileSync(path.join(home, 'share', 'droidasc', 'venv', 'bin', 'python'), '#!/bin/sh\necho "venv:$*"\n', {
    mode: 0o755,
  });
  fs.writeFileSync(path.join(home, 'share', 'droidasc', 'main.py'), '# entry point\n');

  createLinks({ home, files: ['droidasc'], linkDir });
  const entry = path.join(home, 'share', 'droidasc', 'main.py');
  const run = spawnSync(path.join(linkDir, 'droidasc'), ['getmanifest', 'app.apk'], { encoding: 'utf8' });
  assert.equal(run.status, 0, run.stderr);
  assert.equal(run.stdout.trim(), `venv:${entry} getmanifest app.apk`);

  // The same launcher still works when called directly from the store.
  const direct = spawnSync(binPath(home, 'droidasc'), ['getclass', 'app.apk', 'com.poc.Main'], { encoding: 'utf8' });
  assert.equal(direct.status, 0, direct.stderr);
  assert.equal(direct.stdout.trim(), `venv:${entry} getclass app.apk com.poc.Main`);
});
