/**
 * PATH links.  `decx install` exposes every executable it put into
 * `<home>/bin` through the link directory (default `~/.local/bin`): a symlink
 * on POSIX, a generated `.cmd` shim on Windows, where symlinks need developer
 * mode.  A foreign file is never replaced unless `--force` is given, and shell
 * startup files are never touched -- the caller prints the PATH hint instead.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { binRoot } from './config.ts';
import { isWindows } from './platform.ts';

export type LinkStatus = 'created' | 'updated' | 'unchanged' | 'conflict';

export interface LinkOutcome {
  name: string;
  path: string;
  target: string;
  status: LinkStatus;
  reason?: string;
}

export interface LinkOptions {
  home: string;
  /** Executable file names as they sit in `<home>/bin` (e.g. `kuna`, `droidasc.cmd`). */
  files: readonly string[];
  linkDir: string;
  force?: boolean;
  /** Platform override for tests; defaults to the running platform. */
  windows?: boolean;
  log?: (message: string) => void;
}

const SHIM_MARKER = 'Generated by decx install';

/** Command name a managed file is exposed as: `kuna.exe` -> `kuna`, `droidasc.cmd` -> `droidasc`. */
export function linkName(fileName: string): string {
  return fileName.replace(/\.(exe|cmd|bat)$/i, '');
}

/** File name the link directory holds for a command: `kuna` -> `kuna` / `kuna.cmd`. */
export function linkFileName(name: string, windows: boolean = isWindows()): string {
  if (!windows || /\.(exe|cmd|bat)$/i.test(name)) {
    return name;
  }
  return `${name}.cmd`;
}

/** Absolute path of the managed executable a link points at. */
export function linkTarget(home: string, fileName: string): string {
  return path.join(binRoot(home), fileName);
}

/** Windows shim body: forward argv and the exit code to the managed file. */
export function shimText(target: string): string {
  return [
    '@echo off',
    `rem ${SHIM_MARKER}; do not edit.`,
    `"${target}" %*`,
    'exit /b %errorlevel%',
    '',
  ].join('\r\n');
}

/** True when the entry is a link this tool made for the store. */
function isOurs(home: string, linkPath: string, target: string): boolean {
  let stats: fs.Stats;
  try {
    stats = fs.lstatSync(linkPath);
  } catch {
    return false;
  }
  if (stats.isSymbolicLink()) {
    let resolved: string;
    try {
      resolved = path.resolve(path.dirname(linkPath), fs.readlinkSync(linkPath));
    } catch {
      return false;
    }
    if (resolved === path.resolve(target)) {
      return true;
    }
    const bin = path.resolve(binRoot(home));
    return resolved === bin || resolved.startsWith(`${bin}${path.sep}`);
  }
  if (stats.isFile()) {
    try {
      return fs.readFileSync(linkPath, 'utf8').includes(SHIM_MARKER);
    } catch {
      return false;
    }
  }
  return false;
}

/** Remove only an exact link previously created for this executable; foreign entries are untouched. */
export function removeManagedLink(linkDir: string, fileName: string, target: string, windows: boolean = isWindows()): boolean {
  const linked = path.join(linkDir, linkFileName(linkName(fileName), windows));
  try {
    const stat = fs.lstatSync(linked);
    const owned = stat.isSymbolicLink()
      ? path.resolve(path.dirname(linked), fs.readlinkSync(linked)) === path.resolve(target)
      : windows && stat.isFile() && fs.readFileSync(linked, 'utf8') === shimText(target);
    if (owned) {
      fs.unlinkSync(linked);
      return true;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  return false;
}

/** Ownership alone does not mean the entry still points at the desired launcher. */
function isCurrent(linkPath: string, target: string, windows: boolean): boolean {
  try {
    const stats = fs.lstatSync(linkPath);
    if (windows) {
      return stats.isFile() && fs.readFileSync(linkPath, 'utf8') === shimText(target);
    }
    return stats.isSymbolicLink()
      && path.resolve(path.dirname(linkPath), fs.readlinkSync(linkPath)) === path.resolve(target);
  } catch {
    return false;
  }
}

/**
 * Preference between two staged files that map to the same command name: a
 * venv install stages `<tool>` and `<tool>.cmd`, and only one can win the link.
 */
function nativeRank(fileName: string, windows: boolean): number {
  if (!/\.(exe|cmd|bat)$/i.test(fileName)) {
    return windows ? 0 : 2;
  }
  if (!windows) {
    return 1;
  }
  return /\.exe$/i.test(fileName) ? 2 : 1;
}

/** Creates or refreshes the link for every managed executable. */
export function createLinks(options: LinkOptions): LinkOutcome[] {
  const log = options.log ?? ((): void => {});
  const windows = options.windows ?? isWindows();
  const outcomes: LinkOutcome[] = [];
  if (options.files.length === 0) {
    return outcomes;
  }
  fs.mkdirSync(options.linkDir, { recursive: true });
  // Collapse files that share a command name before linking, so the shim never
  // ends up pointing at the POSIX shell launcher on Windows (or vice versa).
  const commands = new Map<string, string>();
  for (const fileName of options.files) {
    const name = linkName(fileName);
    const current = commands.get(name);
    if (current === undefined || nativeRank(fileName, windows) > nativeRank(current, windows)) {
      commands.set(name, fileName);
    }
  }
  for (const fileName of commands.values()) {
    const name = linkName(fileName);
    const target = linkTarget(options.home, fileName);
    const linkPath = path.join(options.linkDir, linkFileName(name, windows));
    const outcome: LinkOutcome = { name, path: linkPath, target, status: 'unchanged' };
    let existing = true;
    try {
      fs.lstatSync(linkPath);
    } catch {
      existing = false;
    }
    const managed = existing && isOurs(options.home, linkPath, target);
    if (managed && isCurrent(linkPath, target, windows)) {
      outcomes.push(outcome);
      continue;
    }
    if (managed) {
      outcome.status = 'updated';
    } else if (existing) {
      if (options.force !== true) {
        outcomes.push({
          ...outcome,
          status: 'conflict',
          reason: `${linkPath} exists and was not created by decx; move it away or re-run with --force`,
        });
        continue;
      }
      const backup = `${linkPath}.decx-old-${process.pid}`;
      fs.renameSync(linkPath, backup);
      log(`moved ${linkPath} to ${backup} (--force)`);
      outcome.status = 'updated';
      outcome.reason = `replaced ${backup}`;
    } else {
      outcome.status = 'created';
    }
    try {
      if (managed) {
        // Remove the entry, never write through an old symlink into its target.
        fs.unlinkSync(linkPath);
      }
      if (windows) {
        fs.writeFileSync(linkPath, shimText(target));
      } else {
        fs.symlinkSync(target, linkPath);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      outcomes.push({ ...outcome, status: 'conflict', reason: `could not create ${linkPath}: ${message}` });
      continue;
    }
    outcomes.push(outcome);
    log(`linked ${name}: ${linkPath} -> ${target}`);
  }
  return outcomes;
}
